cap-java/cds-feature-attachments

- .gitignore
A lot of classes and resources are generated during Maven build. There is no need to put them under version control and they can be ignored.
> Added generated stuff to gitignore, will be generated each build

- cds-feature-attachments/pom.xml
Test dependency to junit is not required and can be removed.
> Remove junit

- cds-feature-attachments/src/main/resources/cds/com.sap.cds/cds-feature-attachments/attachments-annotations.cds
Add annotation @Core.ContentDisposition to get fileName on creation of attachment.
With this annotation added, the Fiori UI sends a request containing the fileName to create the attachments:
```
--batch_id-1729000376682-418
Content-Type:application/http
Content-Transfer-Encoding:binary
POST Books(ID=4a519e61-3c3a-4bd9-ab12-d7e0c5329933,IsActiveEntity=false)/covers HTTP/1.1
Accept:application/json;odata.metadata=minimal;IEEE754Compatible=true
Accept-Language:en-US
Content-Type:application/json;charset=UTF-8;IEEE754Compatible=true
{"fileName":"catweazle.jpg"}
--batch_id-1729000376682-418--
Group ID: $auto
```
See also: https://github.com/cap-js/attachments/blob/898eca7a89a84f15c59ce5a85bea117df19952d2/index.cds#L44
> Add annotation @Core.ContentDisposition to get fileName on creation

- cds-feature-attachments/src/main/resources/cds/com.sap.cds/cds-feature-attachments/attachments-annotations.cds
Add HTML5 CSS annotations to specify column width to be in sync with the Node.js Attachment plugin:
https://github.com/cap-js/attachments/blob/1da65f97d4d358bba5e37acd57682d0375e6f729/index.cds#L36C1-L41C1
> Add HTML5 CSS annotations containing column width

- cds-feature-attachments/pom.xml
- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/handler/applicationservice/helper/ModifyApplicationHandlerHelper.java
- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/handler/applicationservice/processor/modifyevents/DefaultModifyAttachmentEventFactory.java
- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/handler/applicationservice/processor/modifyevents/ModifyAttachmentEventFactory.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/handler/applicationservice/CreateAttachmentsHandlerTest.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/handler/applicationservice/UpdateAttachmentsHandlerTest.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/handler/applicationservice/processor/modifyevents/DefaultModifyAttachmentEventFactoryTest.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/handler/draftservice/DraftPatchAttachmentsHandlerTest.java
This PR removes the parameter `contentIdExist` from method `ModifyAttachmentEvent::processEvent(...)` and adjustst the code and tests accordingly.
> Removed not required parameter contentIdExist

- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/handler/applicationservice/ReadAttachmentsHandler.java
- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/handler/common/ApplicationHandlerHelper.java
- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/handler/common/DefaultAssociationCascader.java
- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/handler/common/model/NodeTree.java
- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/service/handler/transaction/EndTransactionMalwareScanRunner.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/RegistrationFileTest.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/handler/applicationservice/CreateAttachmentsHandlerTest.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/handler/applicationservice/UpdateAttachmentsHandlerTest.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/handler/applicationservice/processor/modifyevents/MarkAsDeletedAttachmentEventTest.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/handler/common/model/NodeTreeTest.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/service/handler/transaction/EndTransactionMalwareScanRunnerTest.java
- integration-tests/srv/src/main/java/com/sap/cds/feature/attachments/integrationtests/testhandler/TestPersistenceHandler.java
- integration-tests/srv/src/test/java/com/sap/cds/feature/attachments/integrationtests/draftservice/DraftOdataRequestValidationBase.java
- integration-tests/srv/src/test/java/com/sap/cds/feature/attachments/integrationtests/draftservice/DraftOdataRequestValidationWithoutTestHandlerAndMalwareScannerTest.java
- integration-tests/srv/src/test/java/com/sap/cds/feature/attachments/integrationtests/nondraftservice/OdataRequestValidationWithoutTestHandlerAndMalwareScannerTest.java
- hide fields and adapt tests
- don't read annotation from base entity -> read from target entity at service
- fixed sonar infos / warnings
> Code quality

- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/configuration/Registration.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/configuration/RegistrationTest.java
- doc/CHANGELOG.md
- [Added support to configure the HTTP client pool](https://github.com/cap-java/cds-feature-attachments/pull/276) to Malware Scanning Service. Supported configuration properties are:
- `cds.attachments.malwareScanner.http.timeout`: The HTTP request timeout in seconds, defaults to 120s
- `cds.attachments.malwareScanner.http.maxConnections`: The max. number of parallel HTTP connections to Malware Scanning Service, defaults to 20 connections
> Increase timeout of HTTP connection to malware scanner

- .github/actions/scan-with-blackduck/action.yaml
- .github/actions/scan-with-sonar/action.yaml
- .github/workflows/main-build.yml
- .github/workflows/pull-request-build.yml
- .pipeline/config.yml
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/configuration/RegistrationTest.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/handler/applicationservice/processor/modifyevents/DefaultModifyAttachmentEventFactoryTest.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/handler/helper/RuntimeHelper.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/service/malware/client/DefaultMalwareScanClientTest.java
- integration-tests/srv/src/test/java/com/sap/cds/feature/attachments/integrationtests/common/JsonToCapMapperTestHelper.java
- integration-tests/srv/src/test/java/com/sap/cds/feature/attachments/integrationtests/common/MalwareScanResultProvider.java
- integration-tests/srv/src/test/java/com/sap/cds/feature/attachments/integrationtests/draftservice/DraftOdataRequestValidationWithTestHandlerTest.java
This PR enables a SonarQube scan for cds-feature-attachments and fixes also the reported issues.
> Sonar scan

- README.md
The following min. required Versions are bumped:
- SAP UI5 to 1.131.0 as it contains a fix for an eTag issue. This fix is required to upload attachment content to an eTag enabled entity, which is the default behavior.
- CAP Java to 3.4.1 as it provides fixes for OData V4 content stream handling. e.g. inline support and correct filenames in case of download.
> Bump min. required versions of CAP Java and SAP UI5

- cds-feature-attachments/pom.xml
The dependency `cds-integration-cloud-sdk` brings a lot transitive dependencies to `cds-feature-attachments`. This PR tries to reduce the number of transitive dependencies as much as possible.
> Cleanup transitive dependencies

- cds-feature-attachments/pom.xml
- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/configuration/Registration.java
- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/service/malware/client/DefaultMalwareScanClient.java
- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/service/malware/client/httpclient/HttpClientProviderFactory.java
- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/service/malware/client/httpclient/MalwareScanClientProviderFactory.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/service/malware/client/DefaultMalwareScanClientTest.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/service/malware/client/httpclient/MalwareScanClientProviderFactoryTest.java
- doc/CHANGELOG.md
- pom.xml
The MalwareScannerService is not tenant aware, so there is no need to use a tenant aware HTTP client pool provided by cds-integration-cloud-sdk.
> Use directly Cloud SDK instead of cds-integration-cloud-sdk

- pom.xml
This PR updates the following dependencies:
- cds-services to 2.10.5
- @sap/cds-dk to 7.9.9
- commons-codec to 1.17.1
Fixes also this CAP issue: https://github.tools.sap/cap/issues/issues/17483
> Update cds-services and cds-dk to latest LTS versions

- .github/dependabot.yml
Currently dependabot doesn't bump the spring-boot version in `integration-tests/pom.xml`. This PR will make dependabot aware of this directory.
See also here: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/controlling-dependencies-updated#defining-multiple-locations-for-manifest-files
> Run dependabot also in integration-tests directory

- .gitignore
During the run of the CAP Notebook a demo application is created in folder cap-notebook/demoapp which has to be ignored by git.
> Add demoapp to gitignore

- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/configuration/Registration.java
This PR fixes a NullPointerException that occurs, if the dependency to cds-feature-attachments is added to pom.xml, but the Outbox is not enabled yet. This happens if the Attachments CDS model is not included yet.
From the application startup log:
```
Caused by: java.lang.NullPointerException: Cannot invoke "com.sap.cds.services.outbox.OutboxService.outboxed(com.sap.cds.services.Service)" because "outbox" is null
at com.sap.cds.feature.attachments.configuration.Registration.eventHandlers(Registration.java:78) ~[cds-feature-attachments-1.0.6.jar:na]
at com.sap.cds.services.impl.runtime.CdsRuntimeConfigurerImpl.lambda$eventHandlerConfigurations$2(CdsRuntimeConfigurerImpl.java:142) ~[cds-services-impl-3.7.2.jar:na]
```
> Fix NullPointerException if OutboxService is not available.

- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/configuration/Registration.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/configuration/RegistrationTest.java
- doc/CHANGELOG.md
Register event handlers on draft service, only if at least one draft service is available. This avoids warning on application startup:
```
WARN 44101 --- [  restartedMain] c.s.c.s.i.h.HandlerRegistryTools         : Failed to register handler method 'public void com.sap.cds.feature.attachments.handler.draftservice.DraftPatchAttachmentsHandler.processBeforeDraftPatch(com.sap.cds.services.draft.DraftPatchEventContext,java.util.List)': Could not find any matching service.
WARN 44101 --- [  restartedMain] c.s.c.s.i.h.HandlerRegistryTools         : Failed to register handler method 'public void com.sap.cds.feature.attachments.handler.draftservice.DraftCancelAttachmentsHandler.processBeforeDraftCancel(com.sap.cds.services.draft.DraftCancelEventContext)': Could not find any matching service.
WARN …
```
> Register event handlers on draft service, only if at least one draft service is available

- integration-tests/pom.xml
- integration-tests/srv/pom.xml
- integration-tests/srv/src/test/java/com/sap/cds/feature/attachments/integrationtests/draftservice/DraftOdataRequestValidationWithoutTestHandlerAndMalwareScannerTest.java
- integration-tests/srv/src/test/java/com/sap/cds/feature/attachments/integrationtests/nondraftservice/OdataRequestValidationWithoutTestHandlerAndMalwareScannerTest.java
- pom.xml
- update dependencies and build plugins
- use artifact `wiremock-spring-boot` from groupId`org.wiremock.integrations` instead of `com.maciejwalkowiak.spring`. See also: https://github.com/wiremock/wiremock-spring-boot?tab=readme-ov-file#credits
> [Maciej Walkowiak](https://github.com/maciejwalkowiak) - This was originally his project and later moved to WireMock organization
> Version bump of some build plugins and dependencies

- .github/dependabot.yml
This PR fixes this error in dependabot:
```
updater | 2025/06/20 15:43:05 ERROR <job_1038064978> Error during file fetching; aborting: /deploy-oss/pom.xml not found
```
> Removed no longer existing directory from dependabot.yml

- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/handler/applicationservice/ReadAttachmentsHandler.java
- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/service/handler/transaction/EndTransactionMalwareScanRunner.java
- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/service/malware/DefaultAttachmentMalwareScanner.java
- cds-feature-attachments/src/main/java/com/sap/cds/feature/attachments/service/malware/client/DefaultMalwareScanClient.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/service/handler/transaction/EndTransactionMalwareScanRunnerTest.java
- cds-feature-attachments/src/test/java/com/sap/cds/feature/attachments/service/malware/DefaultAttachmentMalwareScannerTest.java
Fixes issue: https://github.com/cap-java/cds-feature-attachments/issues/484
> Scan attachments only in certain scan states

- README.md
From my point of view this needs to be more visible and therefore a top-level heading. Do you agree?
> Move Storage Targets section up

- storage-targets/cds-feature-attachments-oss/src/main/java/com/sap/cds/feature/attachments/oss/configuration/Registration.java
- storage-targets/cds-feature-attachments-oss/src/main/java/com/sap/cds/feature/attachments/oss/handler/OSSAttachmentsServiceHandler.java
- storage-targets/cds-feature-attachments-oss/src/main/java/com/sap/cds/feature/attachments/oss/handler/ObjectStoreServiceException.java
- storage-targets/cds-feature-attachments-oss/src/test/java/com/sap/cds/feature/attachments/oss/client/AWSClientIT.java
- storage-targets/cds-feature-attachments-oss/src/test/java/com/sap/cds/feature/attachments/oss/client/AWSClientTest.java
- storage-targets/cds-feature-attachments-oss/src/test/java/com/sap/cds/feature/attachments/oss/client/AzureClientIT.java
- storage-targets/cds-feature-attachments-oss/src/test/java/com/sap/cds/feature/attachments/oss/client/AzureClientTest.java
- storage-targets/cds-feature-attachments-oss/src/test/java/com/sap/cds/feature/attachments/oss/client/GoogleClientIT.java
- storage-targets/cds-feature-attachments-oss/src/test/java/com/sap/cds/feature/attachments/oss/client/GoogleClientTest.java
- storage-targets/cds-feature-attachments-oss/src/test/java/com/sap/cds/feature/attachments/oss/client/MockOSClientTest.java
- storage-targets/cds-feature-attachments-oss/src/test/java/com/sap/cds/feature/attachments/oss/handler/OSSAttachmentsServiceHandlerTest.java
- storage-targets/cds-feature-attachments-oss/src/test/java/com/sap/cds/feature/attachments/oss/handler/OSSAttachmentsServiceHandlerTestUtils.java
This PR contains some improvements for the OSS plugin:
- organize imports
- fixed some sonar issues
- remove not thrown exceptions from method signatures in tests
- reduced visibility of test classes, package private is enough
- fixed Eclipse warnings:
- declare missing serialVersionUID field in serializable class `ObjectStoreServiceException`
- if service binding to object store service is missing, don't instantiate / register OSS handler
> OSS Plugin Cosmetics

- integration-tests/.cdsrc.json
- pom.xml
By default the cds-dk 9.3.0 enables draft messages. In this case the tests behave different and are failing. To ensure that in both version of the cds-dk (8.9.x and 9.3.x) the tests behave the same, the draft messages needs to be disabled.
> Bump CAP Java and cds-dk to latest avaiable versions and disable draft messages in integration tests

- storage-targets/cds-feature-attachments-oss/README.md
After removing the MockOSClient, local development with the cds-feature-attachments-oss is not possible anymore: https://github.com/cap-java/cds-feature-attachments/pull/569
For this, I've added clearer instructions on how to use cds-feature-attachments-oss locally.
> Add explanation for local development to oss README.md
